name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger only on version tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Extract version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore src/MinimalWorker

    - name: Build
      run: dotnet build src/MinimalWorker --configuration Release --no-restore

    - name: Restore dependencies
      run: dotnet restore test/MinimalWorker.Test

    - name: Build
      run: dotnet build test/MinimalWorker.Test --configuration Release --no-restore

    - name: Test
      run: dotnet test test/MinimalWorker.Test --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack src/MinimalWorker --configuration Release --no-build --output ./nupkgs -p:Version=${{ env.VERSION }}

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json